### ISSUE TITLE
3.8.13 源码 build 报错

### ISSUE THREAD

**Issue by EslSuwen** [Vanessa219/vditor#1207]
* 版本：3.8.13 
* 操作系统：macOS 12.3(arm64)

$ npm run build

> vditor@3.8.13 build
> webpack

(node:20038) [DEP_WEBPACK_DEPRECATION_ARRAY_TO_SET] DeprecationWarning: Compilation.modules was changed from Array to Set (using Array method 'reduce' is deprecated)
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:20038) [DEP_WEBPACK_MODULE_ERRORS] DeprecationWarning: Module.errors was removed (use getErrors instead)
(node:20038) [DEP_WEBPACK_COMPILATION_ASSETS] DeprecationWarning: Compilation.assets will be frozen in future, all modifications are deprecated.
BREAKING CHANGE: No more changes should happen to Compilation.assets after sealing the Compilation.
	Do changes to assets earlier, e. g. in Compilation.hooks.processAssets.
	Make sure to select an appropriate stage from Compilation.PROCESS_ASSETS_STAGE_*.
assets by status 15.4 MiB [cached] 295 assets
orphan modules 463 KiB [orphan] 79 modules
runtime modules 1.31 KiB 6 modules
cacheable modules 625 KiB
  modules by path ./src/ts/ 65.8 KiB
    modules by path ./src/ts/markdown/*.ts 38.8 KiB 14 modules
    modules by path ./src/ts/util/*.ts 20.2 KiB 8 modules
    modules by path ./src/ts/ui/*.ts 1.13 KiB 2 modules
    ./src/ts/preview/image.ts 2.9 KiB [built] [code generated]
    ./src/ts/constants.ts 2.81 KiB [built] [code generated]
  modules by path ./src/*.ts 484 KiB
    ./src/index.ts + 74 modules 465 KiB [built] [code generated]
    ./src/method.ts + 4 modules 19.4 KiB [built] [code generated]
  ./src/assets/scss/index.scss 39 bytes [built] [code generated] [1 error]
  ./node_modules/diff-match-patch/index.js 74.7 KiB [built] [code generated]

ERROR in ./src/assets/scss/index.scss (./src/assets/scss/index.scss.webpack[javascript/auto]!=!./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[3].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[3].use[2]!./node_modules/sass-loader/dist/cjs.js!./src/assets/scss/index.scss)
Module Error (from ./node_modules/sass-loader/dist/cjs.js):
Cannot find module 'sass'
Require stack:
- /Users/suwen/Downloads/vditor-3.8.13/vditor-3.8.13/node_modules/sass-loader/dist/utils.js
- /Users/suwen/Downloads/vditor-3.8.13/vditor-3.8.13/node_modules/sass-loader/dist/index.js
- /Users/suwen/Downloads/vditor-3.8.13/vditor-3.8.13/node_modules/sass-loader/dist/cjs.js
- /Users/suwen/Downloads/vditor-3.8.13/vditor-3.8.13/node_modules/loader-runner/lib/loadLoader.js
- /Users/suwen/Downloads/vditor-3.8.13/vditor-3.8.13/node_modules/loader-runner/lib/LoaderRunner.js
- /Users/suwen/Downloads/vditor-3.8.13/vditor-3.8.13/node_modules/webpack/lib/NormalModule.js
- /Users/suwen/Downloads/vditor-3.8.13/vditor-3.8.13/node_modules/webpack/lib/ModuleFilenameHelpers.js
- /Users/suwen/Downloads/vditor-3.8.13/vditor-3.8.13/node_modules/webpack/lib/BannerPlugin.js
- /Users/suwen/Downloads/vditor-3.8.13/vditor-3.8.13/node_modules/webpack/lib/index.js
- /Users/suwen/Downloads/vditor-3.8.13/vditor-3.8.13/node_modules/webpack-cli/lib/webpack-cli.js
- /Users/suwen/Downloads/vditor-3.8.13/vditor-3.8.13/node_modules/webpack-cli/lib/bootstrap.js
- /Users/suwen/Downloads/vditor-3.8.13/vditor-3.8.13/node_modules/webpack-cli/bin/cli.js
- /Users/suwen/Downloads/vditor-3.8.13/vditor-3.8.13/node_modules/webpack/bin/webpack.js
 @ ./src/assets/scss/index.scss
 @ ./src/index.ts 14:0-34

ERROR in ./src/assets/scss/index.scss (./src/assets/scss/index.scss.webpack[javascript/auto]!=!./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[3].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[3].use[2]!./node_modules/sass-loader/dist/cjs.js!./src/assets/scss/index.scss)
Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
Error: PostCSS received undefined instead of CSS string
    at new Input (/Users/suwen/Downloads/vditor-3.8.13/vditor-3.8.13/node_modules/postcss/lib/input.js:24:13)
    at parse (/Users/suwen/Downloads/vditor-3.8.13/vditor-3.8.13/node_modules/postcss/lib/parse.js:8:15)
    at new LazyResult (/Users/suwen/Downloads/vditor-3.8.13/vditor-3.8.13/node_modules/postcss/lib/lazy-result.js:133:16)
    at Processor.process (/Users/suwen/Downloads/vditor-3.8.13/vditor-3.8.13/node_modules/postcss/lib/processor.js:28:14)
    at Object.loader (/Users/suwen/Downloads/vditor-3.8.13/vditor-3.8.13/node_modules/postcss-loader/dist/index.js:87:44)
 @ ./src/assets/scss/index.scss
 @ ./src/index.ts 14:0-34

ERROR in ./src/assets/scss/index.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
HookWebpackError: Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
Error: PostCSS received undefined instead of CSS string
    at new Input (/Users/suwen/Downloads/vditor-3.8.13/vditor-3.8.13/node_modules/postcss/lib/input.js:24:13)
    at parse (/Users/suwen/Downloads/vditor-3.8.13/vditor-3.8.13/node_modules/postcss/lib/parse.js:8:15)
    at new LazyResult (/Users/suwen/Downloads/vditor-3.8.13/vditor-3.8.13/node_modules/postcss/lib/lazy-result.js:133:16)
    at Processor.process (/Users/suwen/Downloads/vditor-3.8.13/vditor-3.8.13/node_modules/postcss/lib/processor.js:28:14)
    at Object.loader (/Users/suwen/Downloads/vditor-3.8.13/vditor-3.8.13/node_modules/postcss-loader/dist/index.js:87:44)
    at tryRunOrWebpackError (/Users/suwen/Downloads/vditor-3.8.13/vditor-3.8.13/node_modules/webpack/lib/HookWebpackError.js:88:9)
    at __webpack_require_module__ (/Users/suwen/Downloads/vditor-3.8.13/vditor-3.8.13/node_modules/webpack/lib/Compilation.js:5049:12)
    at __webpack_require__ (/Users/suwen/Downloads/vditor-3.8.13/vditor-3.8.13/node_modules/webpack/lib/Compilation.js:5006:18)
    at /Users/suwen/Downloads/vditor-3.8.13/vditor-3.8.13/node_modules/webpack/lib/Compilation.js:5077:20
    at symbolIterator (/Users/suwen/Downloads/vditor-3.8.13/vditor-3.8.13/node_modules/neo-async/async.js:3485:9)
    at done (/Users/suwen/Downloads/vditor-3.8.13/vditor-3.8.13/node_modules/neo-async/async.js:3527:9)
    at Hook.eval [as callAsync] (eval at create (/Users/suwen/Downloads/vditor-3.8.13/vditor-3.8.13/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/suwen/Downloads/vditor-3.8.13/vditor-3.8.13/node_modules/tapable/lib/Hook.js:18:14)
    at /Users/suwen/Downloads/vditor-3.8.13/vditor-3.8.13/node_modules/webpack/lib/Compilation.js:4984:43
    at symbolIterator (/Users/suwen/Downloads/vditor-3.8.13/vditor-3.8.13/node_modules/neo-async/async.js:3482:9)
    at timesSync (/Users/suwen/Downloads/vditor-3.8.13/vditor-3.8.13/node_modules/neo-async/async.js:2297:7)
    at Object.eachLimit (/Users/suwen/Downloads/vditor-3.8.13/vditor-3.8.13/node_modules/neo-async/async.js:3463:5)
    at /Users/suwen/Downloads/vditor-3.8.13/vditor-3.8.13/node_modules/webpack/lib/Compilation.js:4949:16
    at symbolIterator (/Users/suwen/Downloads/vditor-3.8.13/vditor-3.8.13/node_modules/neo-async/async.js:3485:9)
    at timesSync (/Users/suwen/Downloads/vditor-3.8.13/vditor-3.8.13/node_modules/neo-async/async.js:2297:7)
    at Object.eachLimit (/Users/suwen/Downloads/vditor-3.8.13/vditor-3.8.13/node_modules/neo-async/async.js:3463:5)
-- inner error --
Error: Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
Error: PostCSS received undefined instead of CSS string
    at new Input (/Users/suwen/Downloads/vditor-3.8.13/vditor-3.8.13/node_modules/postcss/lib/input.js:24:13)
    at parse (/Users/suwen/Downloads/vditor-3.8.13/vditor-3.8.13/node_modules/postcss/lib/parse.js:8:15)
    at new LazyResult (/Users/suwen/Downloads/vditor-3.8.13/vditor-3.8.13/node_modules/postcss/lib/lazy-result.js:133:16)
    at Processor.process (/Users/suwen/Downloads/vditor-3.8.13/vditor-3.8.13/node_modules/postcss/lib/processor.js:28:14)
    at Object.loader (/Users/suwen/Downloads/vditor-3.8.13/vditor-3.8.13/node_modules/postcss-loader/dist/index.js:87:44)
    at Object.<anonymous> (/Users/suwen/Downloads/vditor-3.8.13/vditor-3.8.13/node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[3].use[1]!/Users/suwen/Downloads/vditor-3.8.13/vditor-3.8.13/node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[3].use[2]!/Users/suwen/Downloads/vditor-3.8.13/vditor-3.8.13/node_modules/sass-loader/dist/cjs.js!/Users/suwen/Downloads/vditor-3.8.13/vditor-3.8.13/src/assets/scss/index.scss:1:7)
    at /Users/suwen/Downloads/vditor-3.8.13/vditor-3.8.13/node_modules/webpack/lib/javascript/JavascriptModulesPlugin.js:441:11
    at Hook.eval [as call] (eval at create (/Users/suwen/Downloads/vditor-3.8.13/vditor-3.8.13/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:7:1)
    at Hook.CALL_DELEGATE [as _call] (/Users/suwen/Downloads/vditor-3.8.13/vditor-3.8.13/node_modules/tapable/lib/Hook.js:14:14)
    at /Users/suwen/Downloads/vditor-3.8.13/vditor-3.8.13/node_modules/webpack/lib/Compilation.js:5051:39
    at tryRunOrWebpackError (/Users/suwen/Downloads/vditor-3.8.13/vditor-3.8.13/node_modules/webpack/lib/HookWebpackError.js:83:7)
    at __webpack_require_module__ (/Users/suwen/Downloads/vditor-3.8.13/vditor-3.8.13/node_modules/webpack/lib/Compilation.js:5049:12)
    at __webpack_require__ (/Users/suwen/Downloads/vditor-3.8.13/vditor-3.8.13/node_modules/webpack/lib/Compilation.js:5006:18)
    at /Users/suwen/Downloads/vditor-3.8.13/vditor-3.8.13/node_modules/webpack/lib/Compilation.js:5077:20
    at symbolIterator (/Users/suwen/Downloads/vditor-3.8.13/vditor-3.8.13/node_modules/neo-async/async.js:3485:9)
    at done (/Users/suwen/Downloads/vditor-3.8.13/vditor-3.8.13/node_modules/neo-async/async.js:3527:9)
    at Hook.eval [as callAsync] (eval at create (/Users/suwen/Downloads/vditor-3.8.13/vditor-3.8.13/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/suwen/Downloads/vditor-3.8.13/vditor-3.8.13/node_modules/tapable/lib/Hook.js:18:14)
    at /Users/suwen/Downloads/vditor-3.8.13/vditor-3.8.13/node_modules/webpack/lib/Compilation.js:4984:43
    at symbolIterator (/Users/suwen/Downloads/vditor-3.8.13/vditor-3.8.13/node_modules/neo-async/async.js:3482:9)
    at timesSync (/Users/suwen/Downloads/vditor-3.8.13/vditor-3.8.13/node_modules/neo-async/async.js:2297:7)

Generated code for /Users/suwen/Downloads/vditor-3.8.13/vditor-3.8.13/node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[3].use[1]!/Users/suwen/Downloads/vditor-3.8.13/vditor-3.8.13/node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[3].use[2]!/Users/suwen/Downloads/vditor-3.8.13/vditor-3.8.13/node_modules/sass-loader/dist/cjs.js!/Users/suwen/Downloads/vditor-3.8.13/vditor-3.8.13/src/assets/scss/index.scss
1 | throw new Error("Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):\nError: PostCSS received undefined instead of CSS string\n    at new Input (/Users/suwen/Downloads/vditor-3.8.13/vditor-3.8.13/node_modules/postcss/lib/input.js:24:13)\n    at parse (/Users/suwen/Downloads/vditor-3.8.13/vditor-3.8.13/node_modules/postcss/lib/parse.js:8:15)\n    at new LazyResult (/Users/suwen/Downloads/vditor-3.8.13/vditor-3.8.13/node_modules/postcss/lib/lazy-result.js:133:16)\n    at Processor.process (/Users/suwen/Downloads/vditor-3.8.13/vditor-3.8.13/node_modules/postcss/lib/processor.js:28:14)\n    at Object.loader (/Users/suwen/Downloads/vditor-3.8.13/vditor-3.8.13/node_modules/postcss-loader/dist/index.js:87:44)");
 @ ./src/index.ts 14:0-34

1 error has detailed information that is not shown.
Use 'stats.errorDetails: true' resp. '--stats-error-details' to show it.

webpack 5.70.0 compiled with 3 errors in 4067 ms

**Comment by Vanessa219** [comment]
手动 npm i sass -D
