### ISSUE TITLE
lute会报错, 导致vditor报错: Lute is not defined

### ISSUE THREAD

**Issue by miaobuao** [Vanessa219/vditor#1364]
Vite导入Vditor会报错

<img width="502" alt="image" src="https://user-images.githubusercontent.com/62047803/221120280-4e2c99c6-6922-4a6a-85ce-defc86670f39.png">

```txt
lute.min.js:49 
        
       Uncaught TypeError: Cannot read properties of undefined (reading 'length')
    at Q (lute.min.js:49:4183)
    at Object.$init (lute.min.js:49:61062)
    at Object.$init (lute.min.js:50:91357)
    at Object.$init (lute.min.js:52:81600)
    at Object.$init (lute.min.js:53:270531)
    at Object.$init (lute.min.js:55:318395)
    at $init (lute.min.js:56:2980)
    at r (lute.min.js:4:23874)
    at $runScheduled (lute.min.js:4:24462)
    at $schedule (lute.min.js:4:24639)
    at $go (lute.min.js:4:24362)
    at lute.min.js:60:1
    at lute.min.js:63:4
Q @ lute.min.js:49
$init @ lute.min.js:49
$init @ lute.min.js:50
$init @ lute.min.js:52
$init @ lute.min.js:53
$init @ lute.min.js:55
$init @ lute.min.js:56
r @ lute.min.js:4
$runScheduled @ lute.min.js:4
$schedule @ lute.min.js:4
$go @ lute.min.js:4
(匿名) @ lute.min.js:60
(匿名) @ lute.min.js:63
```

```txt
index.min.js:1 
        
       Uncaught (in promise) ReferenceError: Lute is not defined
    at r2 (index.min.js:1:48861)
    at index.min.js:1:264683
```

**Comment by Vanessa219** [comment]
这个是不是运行环境和浏览器有差异？
直接在浏览器里面是可以运行的。
