### ISSUE TITLE
TypeError: Lute.New is not a function    

### ISSUE THREAD

**Issue by zgpnuaa** [Vanessa219/vditor#1463]
### 编辑模式

* `wysiwyg` 所见即所得模式
* `ir` 即时渲染模式
* `sv` 分屏编辑预览模式

### 描述问题

更新源代码到最新版本后，
根目录运行 npm install
npm run start 启动本地服务器，打开 http://localhost:9000/， 编辑器没问题
npm run build 打包代码到 dist 目录，
再将dist更换到项目中，报如下错误：
```
index.min.js:1 Uncaught (in promise) TypeError: Lute.New is not a function
    at r (index.min.js:1:49138)
    at index.min.js:1:265270
```
换回旧的dist该错误又消失。

项目代码没变化，配置与原来一样：
```
<script>
let currentUser = '{{ request.user.id }}';
    const options = {
				typewriterMode: false,
				cache: {
					enable: false,
				},
				// cdn : "http:127.0.0.1:8000",
				width: '100%',
				height: 150,
				mode: "ir",
				icon:'ant',
				placeholder : '...!',
				toolbar: ['emoji',  'bold', 'italic' ,  '|', 'inline-code' ,'code','|','upload' , ] ,
				preview: {
							markdown: {
								toc: true,
								mark: true,
								footnotes: true,
								autoSpace: true,
							},
							math: {
								engine: 'MathJax',
							},
							hljs: {
							// "lineNumber": true,
							"style": "dracula"
							}
						},
				after(){
						vditor.focus();
						},
				keydown (e) {
						console.log(e);
							if (e.keyCode === 13 && e.shiftKey) {  // enter + return（输入+返回）
								// Handled automatically by textarea（由文本区域自动处理）
							}
							else if(e.keyCode === 13 && !e.shiftKey){ // enter + !return (shift键没有按住，发送消息)
								document.getElementById('id_chat_message_submit').click();
							}
						},		
			};

   var vditor = new Vditor('id_chat_message_input', options);
```
### 期待的结果

期待编辑器正常显示。

### 截屏或录像

![image](https://github.com/Vanessa219/vditor/assets/38033949/6740efba-fb07-496e-91d6-efe8fd97123d)

### 版本信息

* 版本：3.9.5
* 操作系统：ubuntu 22.04
* 浏览器：Chrome 116

### 其他信息

换回旧的dist，该错误又消失。

**Comment by Vanessa219** [comment]
https://github.com/Vanessa219/vditor/blob/be3c101aaecc0cce82b3f36b4cb0e491dc67326c/demo/static.html

参考一下这个。
