### ISSUE TITLE
【问题求助】关于 vditor 直接粘贴时 内容中的图片链接替换出错

### ISSUE THREAD

**Issue by wanStu** [Vanessa219/vditor#1503]
# 【问题求助】关于 vditor 直接粘贴时 内容中的图片链接替换出错

![image.png](https://b3logfile.com/file/2023/11/image-rldKlXy.png)

图中的 linkToImgFormat：

![image.png](https://b3logfile.com/file/2023/11/image-DG5OvTk.png)

这是对应的粘贴文本

```markdown
![Snipaste_2023-08-09_10-47-30.png](https://cdn.nlark.com/yuque/0/2023/png/33773680/1691549289708-16e15b32-984e-4f81-a5ba-030ccdb0c20e.png#averageHue=%23658d78&clientId=u58822d88-dae6-4&from=ui&id=u1957d96e&originHeight=916&originWidth=1920&originalType=binary&ratio=1.3958333730697632&rotation=0&showTitle=false&size=5285722&status=done&style=none&taskId=u14e9c31f-0f4e-46bc-9f7c-aefec201d2e&title=)
```

控制台报错

```javascript
Error handling response: TypeError: Cannot read properties of undefined (reading 'isGulk')
    at chrome-extension://ekbmhggedfdlajiikminikhcjffbleac/js/content.js:12:3444
    at chrome-extension://ekbmhggedfdlajiikminikhcjffbleac/js/content.js:3:8219
data_manage/#/technology/vditor:1 Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.
data_manage/#/technology/vditor:1 Error handling response: TypeError: Cannot read properties of undefined (reading 'clientType')
    at n (chrome-extension://ekbmhggedfdlajiikminikhcjffbleac/js/content.js:13:416)
data_manage/#/technology/vditor:1 Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.
data_manage/#/technology/vditor:1 Error handling response: ReferenceError: stat is not defined
    at chrome-extension://ekbmhggedfdlajiikminikhcjffbleac/js/content.js:12:783
chunk-2d0e59dc.1a5162e4.js:1 linkToImgFormat {msg: '', code: 0, data: {…}}code: 0data: originalURL: "https://cdn.nlark.com/yuque/0/2023/png/33773680/1691549289708-16e15b32-984e-4f81-a5ba-030ccdb0c20e.png#averageHue=%23658d78&clientId=u58822d88-dae6-4&from=ui&id=u1957d96e&originHeight=916&originWidth=1920&originalType=binary&ratio=1.3958333730697632&rotation=0&showTitle=false&size=5285722&status=done&style=none&taskId=u14e9c31f-0f4e-46bc-9f7c-aefec201d2e&title="url: "http://img2.wmnetwork.cc/w/other/202311/23/1700721655_65683.jpg"[[Prototype]]: Objectmsg: ""[[Prototype]]: Object
chunk-9f4098d2.46292b85.js:1 Uncaught TypeError: Cannot set properties of null (setting 'src')
    at i.onreadystatechange (chunk-9f4098d2.46292b85.js:1:170426)
    at d.dispatchEvent (chunk-libs.8fa34ec2.js:248:111387)
    at XMLHttpRequest.h (chunk-libs.8fa34ec2.js:248:109152)
    at d.send [as proxy_send] (chunk-libs.8fa34ec2.js:248:110337)
    at o.XHR.send (app.d23f2f1d.js:1:36684)
    at Object.s [as renderLinkDest] (chunk-9f4098d2.46292b85.js:1:170660)
    at set.v (lute.min.js:61:259948)
    at $b (lute.min.js:60:332692)
    at O (lute.min.js:53:6216)
    at O (lute.min.js:53:6442)
    at O (lute.min.js:53:6442)
    at O (lute.min.js:53:6442)
    at Object.N [as Walk] (lute.min.js:53:5938)
    at $packages.github.com/88250/lute/render.AQ.ptr.Render (lute.min.js:60:332351)
    at $packages.github.com/88250/lute.R.ptr.Md2VditorIRDOM (lute.min.js:61:88214)
    at e.$externalizeWrapper.e.$externalizeWrapper (lute.min.js:5:32068)
    at lute.min.js:7:4085
    at e.$externalizeWrapper.e.$externalizeWrapper [as Md2VditorIRDOM] (lute.min.js:5:32068)
    at chunk-9f4098d2.46292b85.js:1:174532
    at chunk-9f4098d2.46292b85.js:1:146747
    at Object.next (chunk-9f4098d2.46292b85.js:1:146852)
    at chunk-9f4098d2.46292b85.js:1:145787
    at new Promise (<anonymous>)
    at Ke (chunk-9f4098d2.46292b85.js:1:145532)
    at Mt (chunk-9f4098d2.46292b85.js:1:168936)
    at HTMLPreElement.<anonymous> (chunk-9f4098d2.46292b85.js:1:187128)
i.onreadystatechange @ chunk-9f4098d2.46292b85.js:1
dispatchEvent @ chunk-libs.8fa34ec2.js:248
h @ chunk-libs.8fa34ec2.js:248
send @ chunk-libs.8fa34ec2.js:248
o.XHR.send @ app.d23f2f1d.js:1
s @ chunk-9f4098d2.46292b85.js:1
set.v @ lute.min.js:61
$b @ lute.min.js:60
O @ lute.min.js:53
O @ lute.min.js:53
O @ lute.min.js:53
O @ lute.min.js:53
N @ lute.min.js:53
$packages.github.com/88250/lute/render.AQ.ptr.Render @ lute.min.js:60
$packages.github.com/88250/lute.R.ptr.Md2VditorIRDOM @ lute.min.js:61
e.$externalizeWrapper.e.$externalizeWrapper @ lute.min.js:5
(anonymous) @ lute.min.js:7
e.$externalizeWrapper.e.$externalizeWrapper @ lute.min.js:5
(anonymous) @ chunk-9f4098d2.46292b85.js:1
(anonymous) @ chunk-9f4098d2.46292b85.js:1
(anonymous) @ chunk-9f4098d2.46292b85.js:1
(anonymous) @ chunk-9f4098d2.46292b85.js:1
Ke @ chunk-9f4098d2.46292b85.js:1
Mt @ chunk-9f4098d2.46292b85.js:1
(anonymous) @ chunk-9f4098d2.46292b85.js:1
cdn.nlark.com/yuque/0/2023/png/33773680/1691549289708-16e15b32-984e-4f81-a5ba-030ccdb0c20e.png#averageHue=%23658d78&clientId=u58822d88-dae6-4&from=ui&id=u1957d96e&originHeight=916&originWidth=1920&originalType=binary&ratio=1.3958333730697632&rotation=0&showTitle=false&size=5285722&status=done&style=none&taskId=u14e9c31f-0f4e-46bc-9f7c-aefec201d2e&title=:1 
    
    
       GET https://cdn.nlark.com/yuque/0/2023/png/33773680/1691549289708-16e15b32-984e-4f81-a5ba-030ccdb0c20e.png 403 (Forbidden)
Image (async)
m @ chunk-9f4098d2.46292b85.js:1
(anonymous) @ chunk-9f4098d2.46292b85.js:1
(anonymous) @ chunk-9f4098d2.46292b85.js:1
(anonymous) @ chunk-9f4098d2.46292b85.js:1
(anonymous) @ chunk-9f4098d2.46292b85.js:1
Ke @ chunk-9f4098d2.46292b85.js:1
Mt @ chunk-9f4098d2.46292b85.js:1
(anonymous) @ chunk-9f4098d2.46292b85.js:1
cdn.nlark.com/yuque/0/2023/png/33773680/1691549289708-16e15b32-984e-4f81-a5ba-030ccdb0c20e.png#averageHue=%23658d78&clientId=u58822d88-dae6-4&from=ui&id=u1957d96e&originHeight=916&originWidth=1920&originalType=binary&ratio=1.3958333730697632&rotation=0&showTitle=false&size=5285722&status=done&style=none&taskId=u14e9c31f-0f4e-46bc-9f7c-aefec201d2e&title=:1 
    
    
       GET https://cdn.nlark.com/yuque/0/2023/png/33773680/1691549289708-16e15b32-984e-4f81-a5ba-030ccdb0c20e.png 403 (Forbidden)
Image (async)
e.addCaret @ chunk-9f4098d2.46292b85.js:1
e.addToUndoStack @ chunk-9f4098d2.46292b85.js:1
(anonymous) @ chunk-9f4098d2.46292b85.js:1
setTimeout (async)
Ct @ chunk-9f4098d2.46292b85.js:1
dt @ chunk-9f4098d2.46292b85.js:1
(anonymous) @ chunk-9f4098d2.46292b85.js:1
(anonymous) @ chunk-9f4098d2.46292b85.js:1
(anonymous) @ chunk-9f4098d2.46292b85.js:1
(anonymous) @ chunk-9f4098d2.46292b85.js:1
Ke @ chunk-9f4098d2.46292b85.js:1
Mt @ chunk-9f4098d2.46292b85.js:1
(anonymous) @ chunk-9f4098d2.46292b85.js:1
```

**Comment by Vanessa219** [comment]
isGulk 这个好像不是 vditor 里面的东西。

**Comment by wanStu** [comment]
> isGulk 这个好像不是 vditor 里面的东西。
导致换链接失败应该是
chunk-9f4098d2.46292b85.js:1 Uncaught TypeError: Cannot set properties of null (setting 'src')
这一行后面的

**Comment by Vanessa219** [comment]
chunk 这个 js 是？

**Comment by wanStu** [comment]
> chunk 这个 js 是？

应该是 vue 编译之后的代码

**Comment by wanStu** [comment]
> chunk 这个 js 是？

目前发现一个奇怪的现象 在我用本地开发时是可以正常使用的 部署到服务器后就会有这个问题 我需要提供给您其他的什么信息吗

**Comment by Vanessa219** [comment]
这个可能需要你自己单步调试后看一下具体的问题

**Comment by wanStu** [comment]
> 这个可能需要你自己单步调试后看一下具体的问题

好吧 感谢您的对这个问题的关注
