### ISSUE TITLE
Comments dont work

### ISSUE THREAD

**Issue by TheoMcCabe** [Vanessa219/vditor#1535]
### 编辑模式

* `wysiwyg` 所见即所得模式

### 描述问题

When enabling comments - there are errors thrown in the browser. 

This is the code i used to initialise vditor in my vue.js project: 

```    
this.vditor = new Vditor('vditor', {
      mode: 'wysiwyg', // Only allow WYSIWYG mode
      lang: 'en_US',
      toolbarConfig: {
        pin: true,
      },
      cache: {
        enable: false,
      },
      comment: {
        enable: true, 
      },
      toolbar: [ 
        'headings', 'bold', 'italic', 'strike', 'emoji', '|', 
        'line', 
        'quote',
         'list', 
        'ordered-list', 
        'check',
        'code', 'inline-code', 'link', 'table',
        '|', 
         'undo', 'redo', 
        //'|', 
        //'upload', 
        //'fullscreen',
        'edit-mode', 
        //'preview',
        //'outline', 
        //'devtools', 'info', 'help', 'br'
      ],
      input: (value) => {
        store.editorContent = value;
      },
      after: () => {
        this.vditor.setValue(this.initialContent);
      },
```
      
  This is the error that is thrown: 
  
```
  ERROR
e.options.comment.adjustTop is not a function
TypeError: e.options.comment.adjustTop is not a function
    at Ae (webpack-internal:///./node_modules/vditor/dist/index.min.js:2858:90)
    at HTMLPreElement.eval (webpack-internal:///./node_modules/vditor/dist/index.min.js:6064:36)
```

### 期待的结果

I expected there to be no errors

### 截屏或录像

![image](https://github.com/Vanessa219/vditor/assets/9841960/daa1a60b-b3db-4fca-bb52-08dc89e291c9)

### 版本信息

* 版本：3.9.6
* 操作系统：Windows
* 浏览器：Google Chrome

**Comment by Vanessa219** [comment]
参照 https://github.com/Vanessa219/vditor/blob/8ede475d8cbcc65305487ae27b9bc15e94e12193/demo/comment.js
